# Docker Offline Deployment Configuration - HIGH PERFORMANCE
# Xiaozhi ESP32 Server - All Modules
# 
# 高配方案: 18核CPU / 30GB内存
# 适合: 10-20并发用户，中等负载场景

version: '3'
services:
  # Server Module - Python Service
  xiaozhi-esp32-server:
    image: xiaozhi-esp32-server:server_custom
    container_name: xiaozhi-esp32-server
    depends_on:
      xiaozhi-esp32-server-db:
        condition: service_healthy
      xiaozhi-esp32-server-redis:
        condition: service_healthy
      xiaozhi-esp32-server-web:
        condition: service_started
    restart: always
    networks:
      - default
    ports:
      # WebSocket Service
      - "8000:8000"
      # HTTP Service for Vision Analysis
      - "8003:8003"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # Configuration Files
      - ./data:/opt/xiaozhi-esp32-server/data
      # Tool Functions (Hot Reload)
      - ./plugins_func/functions:/opt/xiaozhi-esp32-server/plugins_func/functions
      - ./plugins_func/register.py:/opt/xiaozhi-esp32-server/plugins_func/register.py
      # Memory Module (Hot Reload)
      - ./memory/mem_local_short/mem_local_short.py:/opt/xiaozhi-esp32-server/core/providers/memory/mem_local_short/mem_local_short.py
      # Intent Recognition Module (Hot Reload)
      - ./intent/intent_llm/intent_llm.py:/opt/xiaozhi-esp32-server/core/providers/intent/intent_llm/intent_llm.py
      # Model Files
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
    deploy:
      resources:
        limits:
          cpus: '8'      # 从4核提升到8核
          memory: 16G    # 从8G提升到16G
        reservations:
          cpus: '4'      # 从2核提升到4核
          memory: 8G     # 从4G提升到8G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Web Module - Vue Frontend + Java Backend
  xiaozhi-esp32-server-web:
    image: xiaozhi-esp32-server:web_custom
    container_name: xiaozhi-esp32-server-web
    restart: always
    networks:
      - default
    depends_on:
      xiaozhi-esp32-server-db:
        condition: service_healthy
      xiaozhi-esp32-server-redis:
        condition: service_healthy
    ports:
      # Web Management Console
      - "8002:8002"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_DRUID_URL=jdbc:mysql://xiaozhi-esp32-server-db:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=30000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_DRUID_USERNAME=root
      - SPRING_DATASOURCE_DRUID_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=xiaozhi-esp32-server-redis
      - SPRING_DATA_REDIS_PASSWORD=
      - SPRING_DATA_REDIS_PORT=6379
      # Java性能优化
      - JAVA_OPTS=-Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    volumes:
      # Upload Files
      - ./uploadfile:/uploadfile
      # Docker Configuration (Hot Reload)
      - ./docker-config/start.sh:/start.sh:ro
      - ./docker-config/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: '4'      # 从2核提升到4核
          memory: 8G     # 从4G提升到8G
        reservations:
          cpus: '2'      # 从1核提升到2核
          memory: 4G     # 从2G提升到4G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Database Module - MySQL
  xiaozhi-esp32-server-db:
    image: mysql:latest
    container_name: xiaozhi-esp32-server-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - default
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xiaozhi_esp32_server
      - MYSQL_INITDB_ARGS="--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=2000               # 从1000提升到2000
      - --innodb_buffer_pool_size=2G        # 从512M提升到2G
      - --innodb_log_file_size=256M         # 从128M提升到256M
      - --innodb_flush_log_at_trx_commit=2  # 性能优化
      - --innodb_flush_method=O_DIRECT      # 减少IO
      - --query_cache_size=64M              # 查询缓存
      - --tmp_table_size=64M                # 临时表大小
      - --max_heap_table_size=64M
    deploy:
      resources:
        limits:
          cpus: '4'      # 从2核提升到4核
          memory: 4G     # 从2G提升到4G
        reservations:
          cpus: '2'      # 从1核提升到2核
          memory: 2G     # 从1G提升到2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Module - Cache Service
  xiaozhi-esp32-server-redis:
    image: redis:latest
    container_name: xiaozhi-esp32-server-redis
    restart: always
    networks:
      - default
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
      - redis-server
      - --maxmemory 1536mb              # 从512mb提升到1536mb
      - --maxmemory-policy allkeys-lru
      - --save 900 1
      - --save 300 10
      - --save 60 10000
      - --appendonly yes                # 开启AOF持久化
      - --appendfsync everysec
      - --tcp-backlog 511
      - --timeout 0
      - --tcp-keepalive 300
      - --databases 16
      - --maxclients 10000              # 最大客户端连接数
    volumes:
      - ./redis/data:/data
    deploy:
      resources:
        limits:
          cpus: '2'      # 从1核提升到2核
          memory: 2G     # 从1G提升到2G
        reservations:
          cpus: '1'      # 从0.5核提升到1核
          memory: 1G     # 从512M提升到1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge

